
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.4 EDK_P.49d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_AXI_GPIO_TFT_CONTROL_DEVICE_ID,
		XPAR_AXI_GPIO_TFT_CONTROL_BASEADDR,
		XPAR_AXI_GPIO_TFT_CONTROL_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_TFT_CONTROL_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_TFT_DATA_BUS_DEVICE_ID,
		XPAR_AXI_GPIO_TFT_DATA_BUS_BASEADDR,
		XPAR_AXI_GPIO_TFT_DATA_BUS_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_TFT_DATA_BUS_IS_DUAL
	},
	{
		XPAR_GPIO_LEDS_DEVICE_ID,
		XPAR_GPIO_LEDS_BASEADDR,
		XPAR_GPIO_LEDS_INTERRUPT_PRESENT,
		XPAR_GPIO_LEDS_IS_DUAL
	},
	{
		XPAR_GPIO_PUSH_BUTTONS_DEVICE_ID,
		XPAR_GPIO_PUSH_BUTTONS_BASEADDR,
		XPAR_GPIO_PUSH_BUTTONS_INTERRUPT_PRESENT,
		XPAR_GPIO_PUSH_BUTTONS_IS_DUAL
	},
	{
		XPAR_GPIO_SLIDE_SWITCHES_DEVICE_ID,
		XPAR_GPIO_SLIDE_SWITCHES_BASEADDR,
		XPAR_GPIO_SLIDE_SWITCHES_INTERRUPT_PRESENT,
		XPAR_GPIO_SLIDE_SWITCHES_IS_DUAL
	}
};


