
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.4 EDK_P.49d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xuartlite.h"

/*
* The configuration table for devices
*/

XUartLite_Config XUartLite_ConfigTable[] =
{
	{
		XPAR_UART_BLUETOOTH_DEVICE_ID,
		XPAR_UART_BLUETOOTH_BASEADDR,
		XPAR_UART_BLUETOOTH_BAUDRATE,
		XPAR_UART_BLUETOOTH_USE_PARITY,
		XPAR_UART_BLUETOOTH_ODD_PARITY,
		XPAR_UART_BLUETOOTH_DATA_BITS
	}
};


